export const FETCH_CONTENT = "FETCH_CONTENT";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_FAILED = "FETCH_CONTENT_FAILED";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";
export const UPDATE_CONTENT_FAILED = "UPDATE_CONTENT_FAILED";
